baseurl = "em-bellis.github.io"
title = "Emily S. Bellis, Ph.D."
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->NSF Postdoctoral Research Fellow in Biology <!--]--><br />
		<!--[-->with the <a href="http://www.personal.psu.edu/jrl35/psu/index_JRL.html">Lasky</a> and <a href="http://cwd.huck.psu.edu">dePamphilis</a> labs at Penn State,<!--]--><br />
                <!--[-->studying evolution of genomic interactions. <!--]-->'
  logoimage = "/images/DNA_white.png"
  copyright = "Untitled"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/em_bellis"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/em-bellis"

[languages]
[languages.en]
languageName = "English"
weight = 1
